[package]
name = "tefas-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "parse_document_bench"
harness = false

[features]
default = ["return_single_pass"]
return_single_pass = []
